//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerceG3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billingdb
    {
        public int order_ID { get; set; }
        public string phone_no { get; set; }
        public string prod_name { get; set; }
        public string Bil_Add { get; set; }
        public string ship_Add { get; set; }
        public int Order_Amt { get; set; }
        public string Payment_mode { get; set; }
        public string delivery_date { get; set; }
    }
}
