//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerceG3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public string Phone_no { get; set; }
        public string user_name { get; set; }
        public int Product_ID { get; set; }
        public int product_price { get; set; }
        public int qty { get; set; }
        public int final_pr { get; set; }
    }
}
