//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerceG3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ecomEntities : DbContext
    {
        public ecomEntities()
            : base("name=ecomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_login> admin_login { get; set; }
        public virtual DbSet<Billingdb> Billingdbs { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<cat> cats { get; set; }
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<product_db> product_db { get; set; }
        public virtual DbSet<userdb> userdbs { get; set; }
    }
}
