//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerceG3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_db
    {
        public string Product_name { get; set; }
        public int Product_ID { get; set; }
        public string Description { get; set; }
        public string Product_Cat { get; set; }
        public int Price { get; set; }
        public int qty { get; set; }
    }
}
