//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerceG3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userdb
    {
        public string User_Name { get; set; }
        public string Phone_Number { get; set; }
        public string u_pass { get; set; }
        public string Address_line1 { get; set; }
        public string Address_line2 { get; set; }
        public int Pincode { get; set; }
        public string State { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
    }
}
